workflows:
  metamask-extension-build:
    name: MetaMask Extension Build
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      node: 18
      vars:
        YARN_ENABLE_IMMUTABLE_INSTALLS: "false"

    scripts:
      - name: Install dependencies
        script: |
          corepack enable
          yarn set version stable
          yarn install

      - name: Build MetaMask Extension
        script: |
          yarn build

    artifacts:
      - build/**

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
